export const LISTENER_SERVICE = 'LISTENER_SERVICE';
export const CONTRACT_PROVIDER = 'CONTRACT_PROVIDER';
export const NEW_STAKE_EVENT = 'NEW_STAKE_EVENT';
export const NEW_WINNER_EVENT = 'NEW_WINNER_EVENT';
