export const NEW_STAKE_EVENT = 'NEW_STAKE_EVENT';
export const NEW_WINNER_EVENT = 'NEW_WINNER_EVENT';
export const NEW_GAME_ID = 'NEW_GAME_ID';
export const NEW_WINNING_NUMBER = 'NEW_WINNING_NUMBER';
export const DB_SERVICE_CLIENT = 'DB_SERVICE_CLIENT';
