export default {
  INIT: 'INIT',
  ENABLE_ETHEREUM: 'ENABLE_ETHEREUM',
  LOAD_ACCOUNT_BALANCE: 'LOAD_ACCOUNT_BALANCE',
  LOAD_NETWORK_ID: 'LOAD_NETWORK_ID',
  LOAD_CONTRACT_INSTANCE: 'LOAD_CONTRACT_INSTANCE',
  LOAD_STAKES_TOTAL: 'LOAD_STAKES_TOTAL',
  LOAD_REWARD_BALANCE: 'LOAD_REWARD_BALANCE'
};
