export default {
  GET_CONNECTION_STATUS: 'GET_CONNECTION_STATUS',
  GET_SELECTED_ACCOUNT: 'GET_SELECTED_ACCOUNT',
  GET_NETWORK_ID: 'GET_NETWORK_ID',
  GET_ACCOUNT_BALANCE: 'GET_ACCOUNT_BALANCE',
  GET_CONTRACT_INSTANCE: 'GET_CONTRACT_INSTANCE',
  GET_STAKES_TOTAL: 'GET_STAKES_TOTAL',
  GET_REWARD_BALANCE: 'GET_REWARD_BALANCE'
};
