export default {
  SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
  SET_SELECTED_ACCOUNT: 'SET_SELECTED_ACCOUNT',
  SET_NETWORK_ID: 'SET_NETWORK_ID',
  SET_ACCOUNT_BALANCE: 'SET_ACCOUNT_BALANCE',
  SET_CONTRACT_INSTANCE: 'SET_CONTRACT_INSTANCE',
  SET_STAKES_TOTAL: 'SET_STAKES_TOTAL',
  SET_REWARD_BALANCE: 'SET_REWARD_BALANCE'
};
